### ISSUE TITLE
[Feature Request] Add an explanation on how to use v-tab with vue-router.

### ISSUE THREAD

**Issue by jjloneman** [vuetifyjs/vuetifyjs.com#408] opened 2018-04-08 18:32 UTC
### Problem to solve
The current Vuetify tabs documentation page doesn't specify how to use `v-tab` with `vue-router`. The old 0.17 docs do specify a `to` prop for `v-tabs-item`, but `to` isn't specified in the current api for `v-tab` or any of the other components.

I did eventually get help on the community Discord, where a developer noted that `v-tab` is pretty much a wrapper for `router-link`, so props passed to `v-tab` will also be passed to `router-link`.

### Proposed solution
Other people on other Internet forums have asked the same question as me, so it would be helpful to add an explanation to the [Vuetify Tabs documentation](https://vuetifyjs.com/en/components/tabs).

My [small jsfiddle example](https://jsfiddle.net/jjloneman/e5a6L27u/24/) works now using `v-tab` and `vue-router`, so possibly adding an example like that would be incredibly helpful. Thanks!

**Comment by jacekkarczmarczyk** [comment] 2018-06-13 05:17
Duplicate of #337

**Closed by jacekkarczmarczyk** 2018-06-13 05:17 UTC
