### ISSUE TITLE
[Bug Report] Broken link to view icon values by preset

### ISSUE THREAD

**Issue by Iikeli** [vuetifyjs/vuetifyjs.com#669] opened 2018-11-11 12:52 UTC
### Versions and Environment
**Vuetify:** 1.3.7
**Vue:** 2.5.17
**Browsers:** Firefox 63.0
**OS:** Mac OS 10.14

### Steps to reproduce
Go to `https://vuetifyjs.com/en/framework/icons` and click on `Using a predefined option will prefill defaults based upon the selected preset. This will overwrite the defaults of components that have default icon values. Click *here* to view icon values by preset.`

This is the link behind the `here` `https://github.com/vuetifyjs/vuetify/blob/dev/src/components/Vuetify/mixins/icons.js`

### Expected Behavior
It should lead to a proper page.

### Actual Behavior
It leads to a 404.

### Reproduction Link
<a href="https://github.com/" target="_blank">https://github.com/</a>

**Comment by jacekkarczmarczyk** [comment] 2018-11-11 12:55
Duplicate of https://github.com/vuetifyjs/vuetify/issues/5547

**Closed by jacekkarczmarczyk** 2018-11-11 12:55 UTC
