### ISSUE TITLE
Spacing page is missing documentation of 'all' directions feature.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetifyjs.com#340] opened 2018-03-06 19:55 UTC
Affects: https://vuetifyjs.com/en/layout/spacing

While looking at Vuetify docs through the Chrome Inspector, I noticed that the documentation was using an undocumented spacing feature. This feature allows spacing to be applied to all sides.

```{property}{direction}-{size}```

The class ```.pa-2``` sets padding to all sides.
The class ```.ma-2``` sets margin to all sides.

The ability to apply margin or padding to all sides is not documented on the spacing page.

Resolution: 

Add documentation of this feature to the spacing page.

**Comment by KaelWD** [comment] 2018-03-07 00:46
Duplicate of #294

**Closed by KaelWD** 2018-03-07 00:46 UTC
