### ISSUE TITLE
VDataTable   Service end paging.

### ISSUE THREAD

**Issue by wokill** [vuetifyjs/vuetifyjs.com#439] opened 2018-04-28 06:26 UTC
When using the 'VDataTable' component at the service end of the page, there are twice requests for server-side data when the page is first rendered. Is this the result of a change in pagination, and if so, is there a way to solve this problem? When I tried to use the @update:pagination event, I found that there were two requests for data when the page was initialized. Are the two underlying mechanisms implemented by the same mechanism? Or is there a way to avoid two requests for service data when the page is initialized?

**Comment by hooklife** [comment] 2018-05-07 15:04
I have the same problem。Did you solve this problem?

**Comment by KaelWD** [comment] 2018-05-07 15:27
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

Duplicate of vuetifyjs/vuetify#3585

**Closed by KaelWD** 2018-05-07 15:27 UTC
