### ISSUE TITLE
[Bug]: I find something wrong in version dropdown 

### ISSUE THREAD

**Issue by ElderJames** [vuetifyjs/vuetifyjs.com#214] opened 2018-01-16 04:37 UTC
![image](https://user-images.githubusercontent.com/7550366/34972068-0a4bf75a-faba-11e7-832e-8d6971325b15.png)

**Comment by KaelWD** [comment] 2018-01-16 05:02
Duplicate of vuetifyjs/docs#409

**Closed by KaelWD** 2018-01-16 05:02 UTC
