### ISSUE TITLE
I didn't find description in doc for slot "append" of v-text-field

### ISSUE THREAD

**Issue by Perlover** [vuetifyjs/vuetifyjs.com#683] opened 2018-12-06 13:36 UTC
https://github.com/vuetifyjs/vuetifyjs.com/blob/18dbd0a916754b2733dd737ed80bdd548b1dd44b/src/examples/transitions/todo.vue#L9

**Comment by KaelWD** [comment] 2018-12-06 13:41
Duplicate of #576

This repository is not accepting new issues.

**Closed by KaelWD** 2018-12-06 13:41 UTC
