### ISSUE TITLE
[Bug Report] When options are cleared, there is no message like "no data available"

### ISSUE THREAD

**Issue by akki-jat** [vuetifyjs/vuetifyjs.com#482] opened 2018-05-29 07:31 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.11
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 7

### Steps to reproduce
Click on update button to clear all options

### Expected Behavior
Should display message like "no data"

### Actual Behavior
It does not display anything

### Reproduction Link
[https://codepen.io/akki-jat/pen/qKWeKv](https://codepen.io/akki-jat/pen/qKWeKv)

**Comment by KaelWD** [comment] 2018-05-29 07:43
Duplicate of vuetifyjs/vuetify#2081

This repo is for documentation-specific issues only.

**Closed by KaelWD** 2018-05-29 07:43 UTC
