### ISSUE TITLE
[Bug Report] v-text-field labels need to raise when browser autofill completes the field

### ISSUE THREAD

**Issue by mr6502** [vuetifyjs/vuetifyjs.com#382] opened 2018-03-27 06:24 UTC
![screen shot 2018-03-27 at 13 11 16](https://user-images.githubusercontent.com/21123937/37950286-31446506-31c2-11e8-9af0-6b322a74b0aa.png)
### Versions and Environment
**Vuetify:** 1.0.10
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.11.6

### Steps to reproduce
Fill in a dummy email and password such as

johndoe@example.com
testtest

Allow Chrome browser to offer autosave. Re-visit the page and you will see that the v-text-field labels are rendered over the top of the input text. 

### Expected Behavior
Expect the labels to raise above the input field.

### Actual Behavior
Labels are rendered over the top of the input field text.

### Reproduction Link
[https://codepen.io/mr6502/pen/geXxZQ](https://codepen.io/mr6502/pen/geXxZQ)

### Other comments
This can be achieved by detecting browser autofill within the UI JavaScript:

https://stackoverflow.com/questions/11708092/detecting-browser-autofill

Note, this is not to be confused with autocomplete.

**Comment by jacekkarczmarczyk** [comment] 2018-03-27 09:04
Duplicate of https://github.com/vuetifyjs/vuetify/issues/2792 (and wrong repo)

**Closed by jacekkarczmarczyk** 2018-03-27 09:04 UTC

**Comment by mr6502** [comment] 2018-03-27 09:11
This is not a duplicate of "disabling auto-complete". That's why I wrote "Note, this is not to be confused with autocomplete." in the other comments.

This is render issue with labels when the browser autofill enters text into the v-text-field. In fact you closed #3062 citing #2792.

If it's the wrong repo, please consider leaving an explanation. When I spent 1hr filing a bug report to have it flipped off, it's kinda frustrating, especially when it appears to not be understood.

**Comment by jacekkarczmarczyk** [comment] 2018-03-27 09:24
It is a duplicate, your issue and #3062 and #2792 are caused by the same thing - browser autofill
And this repo is only for bugs with the documentation
