### ISSUE TITLE
application layouts could have links to codepen

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#280] opened 2018-02-14 17:18 UTC
Now there's only link to source code

https://vuetifyjs.com/en/layout/pre-defined

**Comment by bdeo** [comment] 2018-02-26 20:26
Duplicate of #157. Closed via 03a817690afacf74ef5a4f756ef3e2cf5a6c4eee

**Closed by bdeo** 2018-02-26 20:26 UTC
