### ISSUE TITLE
[Feature Request] v-img could not use gradient only just like v-Jumbotrons

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetifyjs.com#590] opened 2018-09-02 10:34 UTC
### Problem to solve
Jumbotrons have been deprecated since v1.2, it is recommended that you use v-img, v-responsive, or a plain div instead. In Jumbotrons, we can use only gradient without any other src for image.

But with v-img, it's not a  case.

### Proposed solution
I would request to have this feature with v-img as well as replacement of v-jumbotrons

**Comment by KaelWD** [comment] 2018-09-02 11:31
Duplicate of vuetifyjs/vuetify#4994

This repo is only for documentation-specific issues.

**Closed by KaelWD** 2018-09-02 11:31 UTC

**Comment by jrvaja** [comment] 2018-09-03 10:51
@KaelWD 
Thanks for your support.
Where could I see this updates?
