### ISSUE TITLE
[Feature Request] [v-data-table] column headers always visible option

### ISSUE THREAD

**Issue by diskman** [vuetifyjs/vuetifyjs.com#471] opened 2018-05-15 20:46 UTC
### Problem to solve
Better usability of v-data-table in case of large number of rows and columns

### Proposed solution
Add configuration property on v-data-table to make columns always visible

**Comment by nekosaur** [comment] 2018-05-16 06:40
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1547

Also issue is on the wrong repo. This is for the vuetify documentation

**Closed by nekosaur** 2018-05-16 06:40 UTC
Labels: duplicate
