### ISSUE TITLE
[Bug Report] Leaving the route "components/forms" returns "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by henriq-88** [vuetifyjs/vuetifyjs.com#686] opened 2018-12-11 06:19 UTC
### Versions and Environment
**Vuetify:** 1.3.12
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.110
**OS:** Mac OS 10.14.1

### Steps to reproduce
Go to /components/form
Go to any other route

### Expected Behavior
Go to new route and load page

### Actual Behavior
Goes to new route but page is blank

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/forms" target="_blank">https://vuetifyjs.com/en/components/forms</a>

**Comment by KaelWD** [comment] 2018-12-11 09:16
Duplicate of #vuetifyjs/vuetify#5633

**Closed by KaelWD** 2018-12-11 09:16 UTC
