### ISSUE TITLE
[Bug Report] v-date-picker is not working properly in v-for

### ISSUE THREAD

**Issue by dtahir57** [vuetifyjs/vuetifyjs.com#424] opened 2018-04-21 06:29 UTC
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.16
**Browsers:** Firefox 59.0
**OS:** Ubuntu undefined

### Steps to reproduce
v-date-picker should work in loops. Or is there anything else , that I am missing?

### Expected Behavior
In v-for , v-date-picker is not working. While it is working out of the loop. 

### Actual Behavior
In v-for, it is throwing an error. The codepen is given as well
The error is -> [Vue warn]: Error in event handler for "input": "TypeError: _vm.$refs.menu2.save is not a function"

### Reproduction Link
[https://codepen.io/danishtahir31/pen/OZVYyw?editors=1112](https://codepen.io/danishtahir31/pen/OZVYyw?editors=1112)

**Comment by KaelWD** [comment] 2018-04-21 06:54
Duplicate of vuetifyjs/vuetify#3466

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Closed by KaelWD** 2018-04-21 06:54 UTC
